apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - name: generate-config
          image: ghcr.io/ocp-on-nerc/snmp-config-generator:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: src-config
              mountPath: /config
            - name: dst-config
              mountPath: /output
          args:
            - generate
            - --mibs-dir=/mibs
            - --generator-path=/config/generator.yaml
            - --output-path=/output/snmp.yaml
      containers:
        - name: snmp-exporter
          image: quay.io/prometheus/snmp-exporter:v0.28.0
          ports:
            - containerPort: 9116
          command:
            - snmp_exporter
          args:
            - --config.file=/config/snmp.yaml
          volumeMounts:
            - name: dst-config
              mountPath: /config
      volumes:
        - name: src-config
          configMap:
            name: generator-config
        - name: dst-config
          emptyDir: {}
