apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: snmp-exporter

resources:
  - deployment.yaml
  - persistentvolumeclaims/generator-config.yaml
  - service.yaml

configMapGenerator:
  - name: generator-scripts
    files:
      - scripts/fetch-snmp-exporter-config.sh
