apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: snmp-exporter

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: generator-config
    files:
      - files/generator.yaml
